#!/usr/bin/env bun
/**
 * Fetch the latest version of each @love-rox/ptpt-* package from the npm
 * registry and write src/lib/versions.ts. Runs as a prebuild step (see
 * package.json scripts) so production deploys always pick up the freshest
 * tag without anyone editing the JSON i18n files.
 *
 * On network failure (offline dev, registry hiccup) or for packages that
 * aren't published yet, the previous value is preserved (defaulting to the
 * pre-release "0.1.0") so the build never breaks.
 */
import fs from "node:fs/promises";
import path from "node:path";

const PACKAGES = ["core", "react", "vue", "rehype", "astro"] as const;
const OUT = path.resolve("src/lib/versions.ts");
const REGISTRY = "https://registry.npmjs.org";

type Latest = Record<(typeof PACKAGES)[number], string>;

async function fetchLatest(pkg: string): Promise<string> {
  const res = await fetch(`${REGISTRY}/@love-rox/ptpt-${pkg}`);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const data = (await res.json()) as { "dist-tags"?: { latest?: string } };
  const v = data["dist-tags"]?.latest;
  if (!v) throw new Error("no dist-tags.latest");
  return v;
}

async function readPrevious(): Promise<Partial<Latest>> {
  try {
    const txt = await fs.readFile(OUT, "utf-8");
    const m = txt.match(/export const VERSIONS = (\{[\s\S]*?\}) as const;/);
    if (!m) return {};
    return JSON.parse(m[1]) as Partial<Latest>;
  } catch {
    return {};
  }
}

async function main() {
  const previous = await readPrevious();
  const out: Partial<Latest> = {};
  for (const p of PACKAGES) {
    try {
      out[p] = await fetchLatest(p);
      console.log(`  ${out[p]}  @love-rox/ptpt-${p}`);
    } catch (e) {
      const fallback = previous[p] ?? "0.1.0";
      out[p] = fallback;
      console.warn(`  ${fallback}  @love-rox/ptpt-${p}  (fetch failed: ${(e as Error).message})`);
    }
  }

  const file = `// AUTO-GENERATED by scripts/fetch-versions.ts.
// Run \`bun run versions\` to refresh; do not hand-edit.

export const VERSIONS = ${JSON.stringify(out, null, 2)} as const;

export type PackageKey = keyof typeof VERSIONS;
`;
  await fs.writeFile(OUT, file);
  console.log(`✓ wrote ${path.relative(process.cwd(), OUT)}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
